[SQLDataBase]
  Server = "postgres"
  Database = "chat"
  User = "postgres"
  Password = "12345"
  ApplicationName = "chat-server"
  MaxIdleConns  = 2
  MaxOpenConns = 2
  ConnMaxLifetime = "5m"
  Port = 5432

[ServerOpt]
  ReadTimeout = "5s"
  WriteTimeout = "5s"
  IdleTimeout = "5s"
